version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          docker:
            - image: circleci/node:10.15.0
          steps:
            - checkout
            - run: npm run deploy
