version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "b1:3f:ab:2f:f5:1c:1a:34:04:5f:8c:e0:a1:31:55:3b"
      - run: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git config user.email "username@mydomain.com"
      - run: git config user.name "My Name"
      - run: npm run deploy
workflows:
  triggers:
    - filters:
        branches:
          ignore:
            - gh-pages
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
      - deploy:
          requires:
            - cypress/run