version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git config user.email "username@mydomain.com"
      - run: git config user.name "My Name"
      - run: npm run deploy
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - cypress/run